Repository Unam3dd/transcendence, pull requests merged in 2023-10, with the labels that each got.

#27 Patch docker compose
  docker-compose-dev.yml
  docker-compose-test.yml
  docker-compose.yml
  package-lock.json
Labels: bug

#35 Backend - All backend is commented without swagger
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
Labels: enhancement, FEATURES

#36 29 implement websocket gateway in backend
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/gateway/events.module.ts
  backend/src/gateway/gateway.ts
Labels: enhancement, FEATURES

#46 44 implementing friends
  .env
  backend/.env
  backend/src/app.module.ts
  backend/src/gateway/gateway.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.guard.ts
  backend/src/modules/friends/dto/create-friends.dto.ts
  backend/src/modules/friends/dto/update-friends.dto.ts
  backend/src/modules/friends/entities/friends.entity.ts
  backend/src/modules/friends/friends.controller.ts
  backend/src/modules/friends/friends.module.ts
  backend/src/modules/friends/friends.service.ts
  backend/src/modules/users/schemas/user.schema.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
Labels: documentation, enhancement, FEATURES

#52 50 sanitize user informations
  Makefile
  backend/src/gateway/gateway.ts
  backend/src/interfaces/user.interfaces.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.guard.ts
  backend/src/modules/friends/dto/create-friends.dto.ts
  backend/src/modules/friends/entities/friends.entity.ts
  backend/src/modules/friends/friends.controller.ts
  backend/src/modules/friends/friends.service.ts
  backend/src/modules/users/schemas/user.schema.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.spec.ts
  backend/src/modules/users/users.service.ts
  backend/test/app.e2e-spec.ts
  frontend/.eslintrc.json
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/chat/chat.component.ts
  frontend/src/app/env.ts
  frontend/src/app/home-page/home-page.component.ts
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/profile-page/profile-page.component.ts
  frontend/src/app/services/cookies.service.ts
  frontend/src/app/services/jwt.service.ts
  frontend/src/app/services/requests.service.ts
  package-lock.json
Labels: documentation, enhancement, FEATURES, norm

#57 Patch Delete method + patch bug in Home Page front when JSON.parse is…
  backend/package-lock.json
  backend/src/interfaces/user.interfaces.ts
  backend/src/modules/auth/auth.guard.ts
  backend/src/modules/users/users.controller.ts
  frontend/src/app/home-page/home-page.component.ts
Labels: bug, enhancement, FEATURES

#63 [Backend/Frontend] 60 implement user status with websocket
  backend/src/gateway/gateway.ts
  backend/src/modules/api/api.service.ts
  backend/src/modules/users/users.controller.ts
  frontend/.eslintrc.json
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/chat/chat.component.ts
  frontend/src/app/enum/status.enum.ts
  frontend/src/app/home-page/home-page.component.ts
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/websocket/websocket.module.ts
  frontend/src/app/websocket/websocket.service.spec.ts
  frontend/src/app/websocket/websocket.service.ts
  frontend/src/app/websocket/websocket.type.ts
Labels: enhancement, FEATURES

#70 68 backend update and protect friends with jwt token and update chat components
  backend/src/gateway/gateway.ts
  backend/src/interfaces/user.interfaces.ts
  backend/src/modules/friends/friends.controller.ts
  backend/src/modules/friends/friends.module.ts
  backend/src/modules/friends/friends.service.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
  frontend/src/app/chat/chat.component.ts
  frontend/src/app/enum/status.enum.ts
  frontend/src/app/interfaces/token.interface.ts
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/services/cookies.service.ts
  frontend/src/app/websocket/websocket.service.ts
Labels: enhancement, FEATURES

#73 62 frontend creating friends component
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/friends/friends.component.html
  frontend/src/app/friends/friends.component.scss
  frontend/src/app/friends/friends.component.spec.ts
  frontend/src/app/friends/friends.component.ts
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/services/requests.service.ts
Labels: enhancement, FEATURES

#74 41 implement change profile feature
  frontend/src/app/services/requests.service.ts
  frontend/src/app/update-profile/update-profile.component.html
  frontend/src/app/update-profile/update-profile.component.ts
Labels: enhancement, FEATURES

#118 89 migration from angular material to boostrap
  backend/package-lock.json
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/users/dto/create-user.dto.ts
  backend/src/modules/users/entities/user.entity.ts
  backend/src/modules/users/users.controller.ts
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/chat-page/chat-page.component.html
  frontend/src/app/chat/chat.component.html
  frontend/src/app/chat/chat.component.ts
  frontend/src/app/friends/friends.component.html
  frontend/src/app/home-page/home-page.component.html
  frontend/src/app/notifications/notifications.component.html
  frontend/src/app/notifications/notifications.component.scss
  frontend/src/app/notifications/notifications.component.spec.ts
  frontend/src/app/notifications/notifications.component.ts
  frontend/src/app/profile-page/profile-page.component.html
  frontend/src/app/profile-page/profile-page.component.ts
  frontend/src/app/register/register.component.html
  frontend/src/app/register/register.component.scss
  frontend/src/app/register/register.component.spec.ts
  frontend/src/app/register/register.component.ts
  frontend/src/app/services/notifications.service.ts
  frontend/src/app/services/requests.service.ts
  frontend/src/app/update-profile/update-profile.component.html
  frontend/src/app/update-profile/update-profile.component.ts
  frontend/src/styles.scss
Labels: FRONTEND, Angular
